import type { 局面 } from "../types";

export const 初期配置: 局面 = {
  盤: [
    [
      { 駒: "香車", 持ち主: "後手" },
      { 駒: "桂馬", 持ち主: "後手" },
      { 駒: "銀将", 持ち主: "後手" },
      { 駒: "金将", 持ち主: "後手" },
      { 駒: "王将", 持ち主: "後手" },
      { 駒: "金将", 持ち主: "後手" },
      { 駒: "銀将", 持ち主: "後手" },
      { 駒: "桂馬", 持ち主: "後手" },
      { 駒: "香車", 持ち主: "後手" },
    ],
    [
      undefined,
      { 駒: "飛車", 持ち主: "後手" },
      undefined,
      undefined,
      undefined,
      undefined,
      undefined,
      { 駒: "角行", 持ち主: "後手" },
      undefined,
    ],
    [
      { 駒: "歩兵", 持ち主: "後手" },
      { 駒: "歩兵", 持ち主: "後手" },
      { 駒: "歩兵", 持ち主: "後手" },
      { 駒: "歩兵", 持ち主: "後手" },
      { 駒: "歩兵", 持ち主: "後手" },
      { 駒: "歩兵", 持ち主: "後手" },
      { 駒: "歩兵", 持ち主: "後手" },
      { 駒: "歩兵", 持ち主: "後手" },
      { 駒: "歩兵", 持ち主: "後手" },
    ],
    [
      undefined,
      undefined,
      undefined,
      undefined,
      undefined,
      undefined,
      undefined,
      undefined,
      undefined,
    ],
    [
      undefined,
      undefined,
      undefined,
      undefined,
      undefined,
      undefined,
      undefined,
      undefined,
      undefined,
    ],
    [
      undefined,
      undefined,
      undefined,
      undefined,
      undefined,
      undefined,
      undefined,
      undefined,
      undefined,
    ],
    [
      { 駒: "歩兵", 持ち主: "先手" },
      { 駒: "歩兵", 持ち主: "先手" },
      { 駒: "歩兵", 持ち主: "先手" },
      { 駒: "歩兵", 持ち主: "先手" },
      { 駒: "歩兵", 持ち主: "先手" },
      { 駒: "歩兵", 持ち主: "先手" },
      { 駒: "歩兵", 持ち主: "先手" },
      { 駒: "歩兵", 持ち主: "先手" },
      { 駒: "歩兵", 持ち主: "先手" },
    ],
    [
      undefined,
      { 駒: "角行", 持ち主: "先手" },
      undefined,
      undefined,
      undefined,
      undefined,
      undefined,
      { 駒: "飛車", 持ち主: "先手" },
      undefined,
    ],
    [
      { 駒: "香車", 持ち主: "先手" },
      { 駒: "桂馬", 持ち主: "先手" },
      { 駒: "銀将", 持ち主: "先手" },
      { 駒: "金将", 持ち主: "先手" },
      { 駒: "王将", 持ち主: "先手" },
      { 駒: "金将", 持ち主: "先手" },
      { 駒: "銀将", 持ち主: "先手" },
      { 駒: "桂馬", 持ち主: "先手" },
      { 駒: "香車", 持ち主: "先手" },
    ],
  ],
  持ち駒: { 先手: [], 後手: [] },
  手番: "先手",
};
